apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: janitchawla/digi:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: react-svc
spec:
  ports:
  - name: http
    port: 80
    nodePort: 31000
    protocol: TCP
    targetPort: 3000
  selector:
    app: react-app
  type: NodePort
